// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsfGhbgVEhubee5QPROsXv8lcRNYwX3xY',
    appId: '1:869906645227:web:a8f53a3faa01922b8ebeae',
    messagingSenderId: '869906645227',
    projectId: 'flutter-test1-98534',
    authDomain: 'flutter-test1-98534.firebaseapp.com',
    storageBucket: 'flutter-test1-98534.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BCwHawvMo5-0azCGVitblLKl3f3YMP8',
    appId: '1:869906645227:android:ee23ee98b2652eb48ebeae',
    messagingSenderId: '869906645227',
    projectId: 'flutter-test1-98534',
    storageBucket: 'flutter-test1-98534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8sgQ34yxDk58OjRo5Pg-tAWU7LdqBfRk',
    appId: '1:869906645227:ios:543eb99ecc03ea058ebeae',
    messagingSenderId: '869906645227',
    projectId: 'flutter-test1-98534',
    storageBucket: 'flutter-test1-98534.firebasestorage.app',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8sgQ34yxDk58OjRo5Pg-tAWU7LdqBfRk',
    appId: '1:869906645227:ios:543eb99ecc03ea058ebeae',
    messagingSenderId: '869906645227',
    projectId: 'flutter-test1-98534',
    storageBucket: 'flutter-test1-98534.firebasestorage.app',
    iosBundleId: 'yes',
  );

}